PACKS = core str
RESULT = fx-predictor
OCAMLBUILD = ocamlbuild -use-ocamlfind
# TODO: Add the `-g` flag for backtrace, if needed.

THREADS = yes

SOURCES = include/Csv.ml include/Csv.mli Types.ml Statistics.ml \
	IO.ml DataRecord.ml Predict.ml NBModel.ml	Main.ml \


-include OCamlMakefile
